title: Solent BEEA
description: Information for students on the BEng (Hons) Electronic Engineering Apprenticeship (BEEA) course
theme: just-the-docs

url: https://axon.github.io/beea

aux_links:
  Website Repository: https://github.com/axon/beea
