title: Solent BEEA
description: Information for students on the BEng (Hons) Electronic Engineering Apprenticeship (BEEA) course
theme: just-the-docs

url: https://axon.github.io/beea

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
